### ISSUE TITLE
Call to a member function setCss()

### ISSUE THREAD

**Issue by bjverde** [bjverde/formDin#119]
````log
PHP Fatal error:  Uncaught Error: Call to a member function setCss() on null in D:\wamp\www\formDin\base\callbacks\onlineSearch.php:124
Stack trace:
#0 D:\wamp\www\formDin\base\classes\webform\TApplication.class.php(806): require_once()
#1 D:\wamp\www\formDin\base\classes\webform\TApplication.class.php(392): TApplication->processRequest()
#2 D:\wamp\www\formDin\appexemplo_v1.0\index.php(129): TApplication->run()
#3 {main}
  thrown in D:\wamp\www\formDin\base\callbacks\onlineSearch.php on line 124
````

**Comment by bjverde** [comment]
Está relacionado com #90
