### ISSUE TITLE
Aba com tecla de atalho fahou

### ISSUE THREAD

**Issue by bjverde** [bjverde/formDin#177]
Aba com tecla de atalho fahou
Aparece o error abaixo
```
[15-Jul-2019 19:31:32 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Maximum function nesting level of '150' reached, aborting! in D:\wamp\www\formDin\base\classes\webform\TElement.class.php:498
Stack trace:
#0 D:\wamp\www\formDin\base\classes\webform\TElement.class.php(575): TElement->subShowCss()
#1 D:\wamp\www\formDin\base\classes\webform\TTable.class.php(88): TElement->show(false)
#2 D:\wamp\www\formDin\base\classes\webform\TElement.class.php(543): TTableRow->show(false)
#3 D:\wamp\www\formDin\base\classes\webform\TElement.class.php(578): TElement->subShowChildren('               ...')
#4 D:\wamp\www\formDin\base\classes\webform\TDisplayControl.class.php(338): TElement->show(false)
#5 D:\wamp\www\formDin\base\classes\webform\TElement.class.php(543): TDisplayControl->show(false)
#6 D:\wamp\www\formDin\base\classes\webform\TElement.class.php(578): TElement->subShowChildren('               ...')
#7 D:\wamp\www\formDin\base\classes\webform\TElement.class.php(543): TElement->show(false)
#8 D:\wamp\www\formDin\base\classes\webform\TElement.class.php(578): TElemen in D:\wamp\www\formDin\base\classes\webform\TElement.class.php on line 498
```

**Comment by bjverde** [comment]
A falha aparece na [v4.7.0 ](https://github.com/bjverde/formDin/commit/fa96da4339c4a48b00d79a6cf15d3901838a7e1f)

No Commit funciona https://github.com/bjverde/formDin/commit/a86c97388dd05156f8e39525fa5e7734b3dc826d

**Comment by bjverde** [comment]
OK - https://github.com/bjverde/formDin/commit/9d3d702246a834473c41e1f6acaa1ddb34d7b097
Ok - Commits on Jun 20, 2019 
OK - https://github.com/bjverde/formDin/commit/9614b8ab77209fd8072a03717ff58ccce9bb098b

**Comment by bjverde** [comment]
Falho - https://github.com/bjverde/formDin/commit/2391cb3dcffeca082c0fe7ece2242d8f3f97c9ea
OK - https://github.com/bjverde/formDin/commit/ba76f9a3766ecb72977c04fe218dea5b83809f63

**Comment by bjverde** [comment]
o problema está em TElement::subShowChildren($result);
